### ISSUE TITLE
Reference moved Amber CLI repository

### ISSUE THREAD

**Issue by HarrisonB** [elorest/cry#7]
It looks like the Amber framework moved their CLI library's framework to [amberframework/amber_cli](https://github.com/amberframework/amber_cli).

Until this is fixed, the installation is broken.

**Comment by elorest** [comment]
CLI is still part of amber stable, latest release, and master. The PR's to approve it haven't been merged.

**Comment by HarrisonB** [comment]
My apologies; it looks like the issue has been resolved by #6 but that just hasn't been released yet.

I'll close this issue.
